### ISSUE TITLE
Support Python 3.6?

### ISSUE THREAD

**Issue by hongquan** [jams2/inotify_lite#2]
Hi @jams2 

I need to access Linux's `inotify` in an old system, CentOS 6 32-bit. I have a [personal copy](https://github.com/hongquan/inotify_lite) of `inotify_lite` with some modification to let it work with Python 3.6 (the newest Python 3 which I can install in this old machine). I just want to ask if you want to merge these modification to `inotify_lite`? I have to ask before submitting PR because I feel that you like some Python 3.8 features (walrus operator, postponed forward annotation) and my modification will cause losing those features.

**Comment by jams2** [comment]
Hi @hongquan ,

I'd be happy to merge your changes, go ahead and submit a pull request. If you could please format the code with [black](https://github.com/psf/black) that would be appreciated (I will add this to the documentation).

Could you give some rationale to your changes to the test cases?

Thanks!

**Comment by jams2** [comment]
Thanks for raising, your changes have been merged and the build pushed to pypi.
