### ISSUE TITLE
Timeout?

### ISSUE THREAD

**Issue by hongquan** [jams2/inotify_lite#4]
I've just realized that `Inotify.read` is blocking. Do you have any idea to support timeout?

**Comment by jams2** [comment]
One way is to use `select` to check if the file descriptor is ready to read, this way you can specify a timeout. It might be better to provide a non-blocking subclass rather than add complexity to the existing class. I will take a look at it later today.

**Comment by jams2** [comment]
Hi @hongquan ,

I've added a read_once method and timeout handling on the `timeout` branch. Does this help with your use case?

**Comment by hongquan** [comment]
Thank you. Will try it.
